"""
Generate 04a_unlearn_cmf_static.ipynb and 04b_unlearn_cmf_posthoc.ipynb
from the shared cells in 04_unlearn_cmf.ipynb.
Run: python notebooks/_make_nb4ab.py
"""
import json, os

SRC = os.path.join(os.path.dirname(__file__), '04_unlearn_cmf.ipynb')
with open(SRC, encoding='utf-8') as f:
    nb_orig = json.load(f)

shared = nb_orig['cells'][:7]   # cells 0-6: markdown title, pip, imports, repo, config, data, helpers

def make_nb(cells, kernel_name='python3'):
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": kernel_name
            },
            "language_info": {"name": "python", "version": "3.10.0"}
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }

def code_cell(cell_id, source_lines):
    return {
        "cell_type": "code",
        "id": cell_id,
        "metadata": {},
        "outputs": [],
        "source": source_lines,
    }

def md_cell(cell_id, source_lines):
    return {
        "cell_type": "markdown",
        "id": cell_id,
        "metadata": {},
        "source": source_lines,
    }

# ─────────────────────────────────────────────────────────────────────────────
# Patch cell 0 (title) for each notebook
# ─────────────────────────────────────────────────────────────────────────────
import copy

def patch_title(cells, new_title_lines):
    patched = copy.deepcopy(cells)
    patched[0]['source'] = new_title_lines
    return patched

# ─────────────────────────────────────────────────────────────────────────────
# NB 04a — CMF-Static
# ─────────────────────────────────────────────────────────────────────────────
title_4a = [
    "# Notebook 04a — CMF-Static Unlearning\n",
    "\n",
    "**Paper:** *An Illusion of Unlearning?* (Gao et al., AISTATS 2026 · arXiv:2604.08271v1)\n",
    "\n",
    "**What this runs:** Stage 1 only — each base method is executed with its CMF-aware training\n",
    "loop (`run_cmf_static`) for the full epoch budget (Table 4 hyperparameters).\n",
    "No post-hoc W-blending stage.\n",
    "Results saved to `results_4a_cmf_static.csv`.\n",
]

cfg_4a_src = [
    "# ── 04a config ──────────────────────────────────────────────────────────────\n",
    "STAGE = '4a'\n",
    "CKPT_ROOT = '/kaggle/working/checkpoints/cmf_paper'\n",
    "os.makedirs(f'{CKPT_ROOT}/cmf_static', exist_ok=True)\n",
    "HPARAM_SOURCE = 'table4'\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f'Stage={STAGE}  device={device}')\n",
]

run_4a_src = [
    "# ── CMF-Static: Stage 1 only ────────────────────────────────────────────────\n",
    "from unlearn.cmf_two_stage import run_cmf_static\n",
    "\n",
    "theta_o_path = f'{CKPT_ROOT_NB1}/pre_train/theta_o_seed{THETA_O_SEED}.pt'\n",
    "if TEST_MODE: theta_o_path = theta_o_path.replace('.pt', '_testmode.pt')\n",
    "assert os.path.exists(theta_o_path), f'Missing theta_o: {theta_o_path}'\n",
    "ck_o = torch.load(theta_o_path, map_location=device)\n",
    "theta_o_state = ck_o.get('model_state_dict', ck_o)\n",
    "\n",
    "results_4a = []\n",
    "\n",
    "for forget_class in FORGET_CLASSES:\n",
    "    for seed in SEEDS:\n",
    "        forget_train_idx = TRAIN_CLASS_IDX[forget_class]\n",
    "        retain_train_idx = [\n",
    "            i for c in range(NUM_CLASSES)\n",
    "            if c != forget_class\n",
    "            for i in TRAIN_CLASS_IDX[c]\n",
    "        ]\n",
    "        retain_loader = torch.utils.data.DataLoader(\n",
    "            torch.utils.data.Subset(full_train, retain_train_idx),\n",
    "            batch_size=128, shuffle=True, num_workers=2)\n",
    "        forget_loader = torch.utils.data.DataLoader(\n",
    "            torch.utils.data.Subset(full_train, forget_train_idx),\n",
    "            batch_size=128, shuffle=True, num_workers=2)\n",
    "        full_train_loader = torch.utils.data.DataLoader(\n",
    "            full_train, batch_size=256, shuffle=False, num_workers=2)\n",
    "        train_retain_eval_ldr = torch.utils.data.DataLoader(\n",
    "            torch.utils.data.Subset(full_train_eval, retain_train_idx),\n",
    "            batch_size=256, shuffle=False, num_workers=2)\n",
    "        train_forget_eval_ldr = torch.utils.data.DataLoader(\n",
    "            torch.utils.data.Subset(full_train_eval, forget_train_idx),\n",
    "            batch_size=256, shuffle=False, num_workers=2)\n",
    "        test_forget_idx = TEST_CLASS_IDX[forget_class]\n",
    "        test_retain_idx = [\n",
    "            i for c in range(NUM_CLASSES)\n",
    "            if c != forget_class\n",
    "            for i in TEST_CLASS_IDX[c]\n",
    "        ]\n",
    "        test_forget_ldr = torch.utils.data.DataLoader(\n",
    "            torch.utils.data.Subset(test_set, test_forget_idx),\n",
    "            batch_size=256, shuffle=False, num_workers=2)\n",
    "        test_retain_ldr = torch.utils.data.DataLoader(\n",
    "            torch.utils.data.Subset(test_set, test_retain_idx),\n",
    "            batch_size=256, shuffle=False, num_workers=2)\n",
    "\n",
    "        for base_method in BASE_METHODS:\n",
    "            for mean_source in MEAN_SOURCES:\n",
    "                cmf_epochs = CMF_EPOCHS_BY_METHOD.get(base_method, 3)\n",
    "                lr    = CMF_LR.get(base_method, 1e-3)\n",
    "                batch = CMF_BATCH.get(base_method, CMF_BATCH_DEFAULT)\n",
    "                tag   = (f'{base_method}_cmf_static_{mean_source}_'\n",
    "                         f'class{forget_class}_seed{seed}')\n",
    "                if TEST_MODE: tag += '_testmode'\n",
    "                ckpt_path = f'{CKPT_ROOT}/cmf_static/{tag}.pt'\n",
    "\n",
    "                if os.path.exists(ckpt_path):\n",
    "                    print(f'[{tag}] exists — skipping.')\n",
    "                    ck = torch.load(ckpt_path, map_location=device)\n",
    "                    results_4a.append(ck['metrics'])\n",
    "                    continue\n",
    "\n",
    "                print(f'\\n[{tag}] cmf_epochs={cmf_epochs}')\n",
    "                torch.manual_seed(seed); np.random.seed(seed); random.seed(seed)\n",
    "\n",
    "                args = make_cmf_args(base_method, lr, cmf_epochs, mean_source,\n",
    "                                     forget_class, forget_train_idx, retain_train_idx,\n",
    "                                     seed=seed)\n",
    "                args.batch_size = batch\n",
    "                if base_method == 'scrub':\n",
    "                    args.scrub_del_bsz  = 64\n",
    "                    args.scrub_sgda_bsz = 64\n",
    "\n",
    "                model = build_cmf_model(args)\n",
    "                model.encoder.load_state_dict(theta_o_state, strict=False)\n",
    "\n",
    "                mean_loader = full_train_loader if mean_source == 'train' else retain_loader\n",
    "                test_loader_full = torch.utils.data.DataLoader(\n",
    "                    test_set, batch_size=256, shuffle=False, num_workers=2)\n",
    "\n",
    "                t0 = time.time()\n",
    "                try:\n",
    "                    model = run_cmf_static(\n",
    "                        base_method=base_method,\n",
    "                        args=args, model=model, device=device,\n",
    "                        retain_loader=retain_loader,\n",
    "                        forget_loader=forget_loader,\n",
    "                        train_loader=mean_loader,\n",
    "                        test_loader=test_loader_full,\n",
    "                        epochs=cmf_epochs,\n",
    "                    )\n",
    "                except Exception as e:\n",
    "                    import traceback; traceback.print_exc()\n",
    "                    print(f'  ERROR: {e}'); continue\n",
    "                wall_min = (time.time() - t0) / 60\n",
    "\n",
    "                model.eval()\n",
    "                model.recompute_cmf(mean_loader, device=device)\n",
    "\n",
    "                metrics = eval_cmf_three_metrics(\n",
    "                    model,\n",
    "                    test_retain_ldr, test_forget_ldr,\n",
    "                    train_retain_eval_ldr, train_forget_eval_ldr\n",
    "                )\n",
    "                metrics.update({\n",
    "                    'method': base_method, 'mean_source': mean_source,\n",
    "                    'forget_class': forget_class, 'seed': seed, 'stage': STAGE,\n",
    "                    'cmf_epochs': cmf_epochs, 'lr': lr, 'batch': batch,\n",
    "                    'wall_clock_minutes': wall_min,\n",
    "                    'n_forget_train': len(forget_train_idx),\n",
    "                    'n_retain_train': len(retain_train_idx),\n",
    "                    'protocol': 'whole_class_single',\n",
    "                    'hparam_source': HPARAM_SOURCE,\n",
    "                })\n",
    "\n",
    "                torch.save({\n",
    "                    'model_state_dict': model.state_dict(),\n",
    "                    'config': {\n",
    "                        'base_method': base_method, 'mean_source': mean_source,\n",
    "                        'dataset': DATASET, 'arch': ARCH, 'num_classes': NUM_CLASSES,\n",
    "                        'forget_class': forget_class, 'seed': seed,\n",
    "                        'cmf_epochs': cmf_epochs, 'lr': lr, 'batch': batch,\n",
    "                        'protocol': 'whole_class_single',\n",
    "                        'hparam_source': HPARAM_SOURCE,\n",
    "                        'repo_commit': REPO_COMMIT, 'test_mode': TEST_MODE,\n",
    "                    },\n",
    "                    'seed': seed, 'metrics': metrics,\n",
    "                }, ckpt_path)\n",
    "                print(f'  Saved {ckpt_path}')\n",
    "                print(f'  out  R={metrics[\"output_retain_acc\"]:.2f}%  '\n",
    "                      f'F={metrics[\"output_forget_acc\"]:.2f}%')\n",
    "                print(f'  ncc  R={metrics[\"ncc_retain_acc\"]:.2f}%  '\n",
    "                      f'F={metrics[\"ncc_forget_acc\"]:.2f}%')\n",
    "                results_4a.append(metrics)\n",
    "\n",
    "df_4a = pd.DataFrame(results_4a)\n",
    "df_4a.to_csv(f'{CKPT_ROOT}/results_4a_cmf_static.csv', index=False)\n",
    "print('\\n=== CMF-Static results saved ===')\n",
    "if not df_4a.empty:\n",
    "    metric_cols = ['output_retain_acc','output_forget_acc',\n",
    "                   'probe_retain_acc','probe_forget_acc','ncc_retain_acc','ncc_forget_acc']\n",
    "    print('\\n=== Mean across all forget classes ===')\n",
    "    print(df_4a.groupby('method')[metric_cols].mean().round(2).to_string())\n",
]

# ─────────────────────────────────────────────────────────────────────────────
# NB 04b — CMF-Post-hoc (k=2, Stage 1 = No-CMF, Stage 2 = k CMF epochs)
# ─────────────────────────────────────────────────────────────────────────────
title_4b = [
    "# Notebook 04b — CMF-Post-hoc Unlearning (k=2)\n",
    "\n",
    "**Paper:** *An Illusion of Unlearning?* (Gao et al., AISTATS 2026 · arXiv:2604.08271v1)\n",
    "\n",
    "**What this runs:** Two-stage post-hoc CMF correction.\n",
    "- **Stage 1:** Standard (No-CMF) unlearning identical to NB3, using the same epoch budget.\n",
    "- **Stage 2:** k=2 additional CMF-aware epochs on retain+forget data.\n",
    "  The CMF head W is recomputed after Stage 2.\n",
    "Results saved to `results_4b_cmf_posthoc.csv`.\n",
]

cfg_4b_src = [
    "# ── 04b config ──────────────────────────────────────────────────────────────\n",
    "STAGE        = '4b'\n",
    "K_POSTHOC    = 2          # number of extra CMF epochs added after Stage 1\n",
    "PHASE2_DATA  = 'retain_plus_forget'  # data used in Stage 2\n",
    "CKPT_ROOT    = '/kaggle/working/checkpoints/cmf_paper'\n",
    "os.makedirs(f'{CKPT_ROOT}/cmf_posthoc', exist_ok=True)\n",
    "HPARAM_SOURCE = 'table4'\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f'Stage={STAGE}  K_POSTHOC={K_POSTHOC}  phase2_data={PHASE2_DATA}  device={device}')\n",
]

run_4b_src = [
    "# ── CMF-Post-hoc: Stage1=No-CMF, Stage2=k CMF epochs ───────────────────────\n",
    "from unlearn.cmf_two_stage import cmf_two_stage_unlearn\n",
    "from unlearn import unlear_func\n",
    "\n",
    "# Stage 1 uses the plain (No-CMF) unlearn functions from NB3\n",
    "NB3_LR = {\n",
    "    'scrub':               1e-4,\n",
    "    'grad_ascent_descent': 1e-4,\n",
    "    'random_label':        1e-4,\n",
    "    'salun':               1e-4,\n",
    "    'tarun':               5e-5,\n",
    "}\n",
    "NB3_EPOCHS = {\n",
    "    'random_label': 1 if TEST_MODE else 3,\n",
    "    'salun':        1 if TEST_MODE else 3,\n",
    "    'grad_ascent_descent': 1 if TEST_MODE else 3,\n",
    "    'scrub':        1 if TEST_MODE else 3,\n",
    "    'tarun':        1 if TEST_MODE else 3,\n",
    "}\n",
    "\n",
    "theta_o_path = f'{CKPT_ROOT_NB1}/pre_train/theta_o_seed{THETA_O_SEED}.pt'\n",
    "if TEST_MODE: theta_o_path = theta_o_path.replace('.pt', '_testmode.pt')\n",
    "assert os.path.exists(theta_o_path), f'Missing theta_o: {theta_o_path}'\n",
    "ck_o = torch.load(theta_o_path, map_location=device)\n",
    "theta_o_state = ck_o.get('model_state_dict', ck_o)\n",
    "\n",
    "results_4b = []\n",
    "\n",
    "for forget_class in FORGET_CLASSES:\n",
    "    for seed in SEEDS:\n",
    "        forget_train_idx = TRAIN_CLASS_IDX[forget_class]\n",
    "        retain_train_idx = [\n",
    "            i for c in range(NUM_CLASSES)\n",
    "            if c != forget_class\n",
    "            for i in TRAIN_CLASS_IDX[c]\n",
    "        ]\n",
    "        retain_loader = torch.utils.data.DataLoader(\n",
    "            torch.utils.data.Subset(full_train, retain_train_idx),\n",
    "            batch_size=128, shuffle=True, num_workers=2)\n",
    "        forget_loader = torch.utils.data.DataLoader(\n",
    "            torch.utils.data.Subset(full_train, forget_train_idx),\n",
    "            batch_size=128, shuffle=True, num_workers=2)\n",
    "        # retain+forget combined for Stage 2\n",
    "        retain_forget_loader = torch.utils.data.DataLoader(\n",
    "            torch.utils.data.Subset(full_train, retain_train_idx + forget_train_idx),\n",
    "            batch_size=128, shuffle=True, num_workers=2)\n",
    "        full_train_loader = torch.utils.data.DataLoader(\n",
    "            full_train, batch_size=256, shuffle=False, num_workers=2)\n",
    "        train_retain_eval_ldr = torch.utils.data.DataLoader(\n",
    "            torch.utils.data.Subset(full_train_eval, retain_train_idx),\n",
    "            batch_size=256, shuffle=False, num_workers=2)\n",
    "        train_forget_eval_ldr = torch.utils.data.DataLoader(\n",
    "            torch.utils.data.Subset(full_train_eval, forget_train_idx),\n",
    "            batch_size=256, shuffle=False, num_workers=2)\n",
    "        test_forget_idx = TEST_CLASS_IDX[forget_class]\n",
    "        test_retain_idx = [\n",
    "            i for c in range(NUM_CLASSES)\n",
    "            if c != forget_class\n",
    "            for i in TEST_CLASS_IDX[c]\n",
    "        ]\n",
    "        test_forget_ldr = torch.utils.data.DataLoader(\n",
    "            torch.utils.data.Subset(test_set, test_forget_idx),\n",
    "            batch_size=256, shuffle=False, num_workers=2)\n",
    "        test_retain_ldr = torch.utils.data.DataLoader(\n",
    "            torch.utils.data.Subset(test_set, test_retain_idx),\n",
    "            batch_size=256, shuffle=False, num_workers=2)\n",
    "\n",
    "        for base_method in BASE_METHODS:\n",
    "            for mean_source in MEAN_SOURCES:\n",
    "                s1_epochs = NB3_EPOCHS.get(base_method, 3)\n",
    "                s1_lr     = NB3_LR.get(base_method, 1e-4)\n",
    "                cmf_lr    = CMF_LR.get(base_method, 1e-3)\n",
    "                batch     = CMF_BATCH.get(base_method, CMF_BATCH_DEFAULT)\n",
    "                tag = (f'{base_method}_cmf_posthoc_k{K_POSTHOC}_{mean_source}_'\n",
    "                       f'class{forget_class}_seed{seed}')\n",
    "                if TEST_MODE: tag += '_testmode'\n",
    "                ckpt_path = f'{CKPT_ROOT}/cmf_posthoc/{tag}.pt'\n",
    "\n",
    "                if os.path.exists(ckpt_path):\n",
    "                    print(f'[{tag}] exists — skipping.')\n",
    "                    ck = torch.load(ckpt_path, map_location=device)\n",
    "                    results_4b.append(ck['metrics'])\n",
    "                    continue\n",
    "\n",
    "                print(f'\\n[{tag}] s1_epochs={s1_epochs} k_posthoc={K_POSTHOC}')\n",
    "                torch.manual_seed(seed); np.random.seed(seed); random.seed(seed)\n",
    "\n",
    "                # Stage 1 args — plain No-CMF method\n",
    "                import argparse as _ap\n",
    "                args_s1 = _ap.Namespace(\n",
    "                    dataset=DATASET, arch=ARCH, num_classes=NUM_CLASSES,\n",
    "                    class_label_names=list(range(NUM_CLASSES)),\n",
    "                    unlearn_method=base_method,\n",
    "                    unlearn_class=[forget_class],\n",
    "                    batch_size=batch, test_batch_size=256,\n",
    "                    lr=s1_lr, momentum=0.9, weight_decay=5e-4,\n",
    "                    epochs_or_steps=s1_epochs, seed=seed,\n",
    "                    num_retain_samples=len(retain_train_idx),\n",
    "                    num_forget_samples=len(forget_train_idx),\n",
    "                    grad_norm_clip=1.0,\n",
    "                    SVD_alpha_r=1000, SVD_alpha_f=30, SVD_samples=900, SVD_max_patches=10000,\n",
    "                    freeze_except_last=False,\n",
    "                    scrub_del_bsz=64, scrub_sgda_bsz=64, scrub_msteps=2, scrub_epochs=s1_epochs,\n",
    "                    salun_threshold=0.5,\n",
    "                    tarun_impair_lr=s1_lr, tarun_samples_per_class=1000,\n",
    "                    dry_run=TEST_MODE, no_cuda=False, no_mps=True, gamma=0.5,\n",
    "                    data_path='/kaggle/working/data',\n",
    "                    remove_FC=False, CMFClassifier=False,\n",
    "                    pretrained=False, temperature=1.0,\n",
    "                    prob_batch_size=256, lp_every=0,\n",
    "                    mean_source=mean_source,\n",
    "                    repo_commit=REPO_COMMIT, test_mode=TEST_MODE,\n",
    "                )\n",
    "                # Stage 2 args — CMF-aware fine-tune\n",
    "                args_s2 = make_cmf_args(base_method, cmf_lr, K_POSTHOC, mean_source,\n",
    "                                        forget_class, forget_train_idx, retain_train_idx,\n",
    "                                        seed=seed)\n",
    "                args_s2.batch_size = batch\n",
    "                if base_method == 'scrub':\n",
    "                    args_s1.scrub_del_bsz  = 64\n",
    "                    args_s1.scrub_sgda_bsz = 64\n",
    "                    args_s2.scrub_del_bsz  = 64\n",
    "                    args_s2.scrub_sgda_bsz = 64\n",
    "\n",
    "                # Build plain encoder model for Stage 1\n",
    "                from unlearn.cmf_weights import ModelModule\n",
    "                from unlearn.cmf_weights import ModelModule as _MM\n",
    "                import copy as _copy\n",
    "                plain_args = _copy.copy(args_s1)\n",
    "                plain_args.remove_FC = False\n",
    "                plain_args.CMFClassifier = False\n",
    "                # Use a standard resnet18 loaded from theta_o\n",
    "                import torchvision.models as tvm\n",
    "                import torch.nn as _nn\n",
    "                plain_model = tvm.resnet18(pretrained=False)\n",
    "                plain_model.fc = _nn.Linear(plain_model.fc.in_features, NUM_CLASSES)\n",
    "                plain_model = plain_model.to(device)\n",
    "                plain_model.load_state_dict(theta_o_state, strict=True)\n",
    "\n",
    "                mean_loader = full_train_loader if mean_source == 'train' else retain_loader\n",
    "                test_loader_full = torch.utils.data.DataLoader(\n",
    "                    test_set, batch_size=256, shuffle=False, num_workers=2)\n",
    "                phase2_loader = retain_forget_loader  # retain+forget for Stage 2\n",
    "\n",
    "                t0 = time.time()\n",
    "                try:\n",
    "                    model = cmf_two_stage_unlearn(\n",
    "                        base_method=base_method,\n",
    "                        args_s1=args_s1, args_s2=args_s2,\n",
    "                        model=plain_model, device=device,\n",
    "                        retain_loader=retain_loader,\n",
    "                        forget_loader=forget_loader,\n",
    "                        phase2_loader=phase2_loader,\n",
    "                        train_loader=mean_loader,\n",
    "                        test_loader=test_loader_full,\n",
    "                        stage1_epochs=s1_epochs,\n",
    "                        stage2_epochs=K_POSTHOC,\n",
    "                    )\n",
    "                except Exception as e:\n",
    "                    import traceback; traceback.print_exc()\n",
    "                    print(f'  ERROR: {e}'); continue\n",
    "                wall_min = (time.time() - t0) / 60\n",
    "\n",
    "                model.eval()\n",
    "                model.recompute_cmf(mean_loader, device=device)\n",
    "\n",
    "                metrics = eval_cmf_three_metrics(\n",
    "                    model,\n",
    "                    test_retain_ldr, test_forget_ldr,\n",
    "                    train_retain_eval_ldr, train_forget_eval_ldr\n",
    "                )\n",
    "                metrics.update({\n",
    "                    'method': base_method, 'mean_source': mean_source,\n",
    "                    'stage': STAGE, 'k_posthoc': K_POSTHOC,\n",
    "                    'phase2_data': PHASE2_DATA,\n",
    "                    'forget_class': forget_class, 'seed': seed,\n",
    "                    'wall_clock_minutes': wall_min,\n",
    "                    'n_forget_train': len(forget_train_idx),\n",
    "                    'n_retain_train': len(retain_train_idx),\n",
    "                    'protocol': 'whole_class_single',\n",
    "                    'hparam_source': HPARAM_SOURCE,\n",
    "                })\n",
    "\n",
    "                torch.save({\n",
    "                    'model_state_dict': model.state_dict(),\n",
    "                    'config': {\n",
    "                        'base_method': base_method, 'mean_source': mean_source,\n",
    "                        'dataset': DATASET, 'arch': ARCH, 'num_classes': NUM_CLASSES,\n",
    "                        'forget_class': forget_class, 'seed': seed,\n",
    "                        'k_posthoc': K_POSTHOC, 'phase2_data': PHASE2_DATA,\n",
    "                        'protocol': 'whole_class_single',\n",
    "                        'hparam_source': HPARAM_SOURCE,\n",
    "                        'repo_commit': REPO_COMMIT, 'test_mode': TEST_MODE,\n",
    "                    },\n",
    "                    'seed': seed, 'metrics': metrics,\n",
    "                }, ckpt_path)\n",
    "                print(f'  Saved {ckpt_path}')\n",
    "                print(f'  out  R={metrics[\"output_retain_acc\"]:.2f}%  '\n",
    "                      f'F={metrics[\"output_forget_acc\"]:.2f}%')\n",
    "                print(f'  ncc  R={metrics[\"ncc_retain_acc\"]:.2f}%  '\n",
    "                      f'F={metrics[\"ncc_forget_acc\"]:.2f}%')\n",
    "                results_4b.append(metrics)\n",
    "\n",
    "df_4b = pd.DataFrame(results_4b)\n",
    "df_4b.to_csv(f'{CKPT_ROOT}/results_4b_cmf_posthoc.csv', index=False)\n",
    "print('\\n=== CMF-Post-hoc results saved ===')\n",
    "if not df_4b.empty:\n",
    "    metric_cols = ['output_retain_acc','output_forget_acc',\n",
    "                   'probe_retain_acc','probe_forget_acc','ncc_retain_acc','ncc_forget_acc']\n",
    "    print('\\n=== Mean across all forget classes ===')\n",
    "    print(df_4b.groupby('method')[metric_cols].mean().round(2).to_string())\n",
]

# ─────────────────────────────────────────────────────────────────────────────
# Assemble and write notebooks
# ─────────────────────────────────────────────────────────────────────────────
cells_4a = patch_title(shared, title_4a) + [
    code_cell('cfg-4a', cfg_4a_src),
    code_cell('run-4a', run_4a_src),
]

cells_4b = patch_title(shared, title_4b) + [
    code_cell('cfg-4b', cfg_4b_src),
    code_cell('run-4b', run_4b_src),
]

out_4a = os.path.join(os.path.dirname(__file__), '04a_unlearn_cmf_static.ipynb')
out_4b = os.path.join(os.path.dirname(__file__), '04b_unlearn_cmf_posthoc.ipynb')

with open(out_4a, 'w', encoding='utf-8') as f:
    json.dump(make_nb(cells_4a), f, indent=1, ensure_ascii=False)
with open(out_4b, 'w', encoding='utf-8') as f:
    json.dump(make_nb(cells_4b), f, indent=1, ensure_ascii=False)

print(f'Written: {out_4a}')
print(f'Written: {out_4b}')
